### ISSUE TITLE
Unable to use with macOS targets

### ISSUE THREAD

**Issue by tonyarnold** [kelvin13/swift-opengl#1]
It's up to you whether you want to address this, but the system-provided OpenGL.framework on macOS is imported via:

```swift
import OpenGL
```

Which is exactly the same import as this library. I believe this means that your library cannot be imported into a project targeting macOS.

**Comment by tayloraswift** [comment]
What if the library was renamed to just “GL”?

```swift
import GL 
```

**Comment by tonyarnold** [comment]
Yup, that'd probably do it! Unfortunately, the XML library this one depends on imports Glibc. Sorry for dumping issues on you, I'll try to have a look and submit a PR later tonight.

**Comment by tayloraswift** [comment]
Yeah, luckily that one has an easy fix, just swap out `Glibc` for `Darwin` and everything should work fine. Or use a hacky preprocessor directive. I held off doing that previously because I assumed by now Swift would support a unified `import C` or something.

**Comment by tayloraswift** [comment]
Renamed the package to `GL` and pushed the `Darwin` fix to `swiftxml`.
